project:
  type: website

website:
  title: "IS428 Project "
  navbar:
    left:
      - text: Introduction 
        href: intro.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - united
      - brand
    css: styles.css
    toc: true

editor: visual

